### PR TITLE
Fix invalid entity client error

### PR DESCRIPTION
**Pull request by sbzlzh**
It does solve the problem with #1171. could the code in line 46 also be used in line 38.

### CODE REVIEW

**Comment by sbzlzh** [comment]
This is before it's used.
image

This is after use
image

**Comment by TimGoll** [comment]
@saibotk @Histalek What is your opinion on this?

My first thought was "oh, no, this shouldn't be in there. But on a second though this might be alright? Because a player, that is disconnected, is no spec.

Might cause problems with checks that are `if not ply:IsSpec` though

**Comment by sbzlzh** [comment]
> @saibotk @Histalek What is your opinion on this?
> 
> My first thought was "oh, no, this shouldn't be in there. But on a second though this might be alright? Because a player, that is disconnected, is no spec.
> 
> Might cause problems with checks that are `if not ply:IsSpec` though

There may be more than one way to do this, let's see if you have any others.

**Comment by TimGoll** [comment]
> > @saibotk @Histalek What is your opinion on this?
> > My first thought was "oh, no, this shouldn't be in there. But on a second though this might be alright? Because a player, that is disconnected, is no spec.
> > Might cause problems with checks that are `if not ply:IsSpec` though
> 
> There may be more than one way to do this, let's see if you have any others.

I'd have fixed this where the issue occurs. In the lines where IsSpec is called.

**Comment by Histalek** [comment]
> > > @saibotk @Histalek What is your opinion on this?
> > > My first thought was "oh, no, this shouldn't be in there. But on a second though this might be alright? Because a player, that is disconnected, is no spec.
> > > Might cause problems with checks that are `if not ply:IsSpec` though
> > 
> > 
> > There may be more than one way to do this, let's see if you have any others.
> 
> I'd have fixed this where the issue occurs. In the lines where IsSpec is called.

Yes that should be the way. Whoever calls this should make sure they do so on a valid entity. I'm against shifting the responsibility to the called function.

**Comment by Histalek** [comment]
will be fixed by #1180

**Pull request closed without merging**
