### PR TITLE
Equipment Menu: command for opening a specific tab

### PR DESCRIPTION
**Pull request by Spanospy**
Mainly throwing this pull request to get some feedback/opinions on adding this.

My use case is that I want my addon to be able to display a tab it adds, for example when a user presses a keybind for it. For now I just have it open the tab as soon as it's brought: [link](https://github.com/Spanospy/ttt2-item_beacon_hacker/blob/2c38a74c62646fd67bc4e79c3ff0283214e50d42/lua/terrortown/entities/items/item_beacon_hacker.lua#L107)

The way this is implemented also allows users to make their own bindings to quickly open the transfer, radio or disguise tabs, if they so wish.

I am aware that this half-a-decade old equipment menu is probably due for a overhaul, even if just UI wise. Still, I feel like the idea of this functionality could be useful to have.

### CODE REVIEW

**Comment by TimGoll** [comment]
First of, yes, a Shop UI and backend overhaul is in the works right now!

Regarding your additions. Why did you chose commands for this? 

I understand your reasoning that some equipment items want a possibility to directly open a tab, but this would be also possible with a function call.

If you want bindings, I'd like to vote against commands as we do not want to make the user use the console.

I'd appreciate an API that allows you to open tabs (or whatever it is that we will have after the rework)

That way you can

- open the menu with function calls in addons
- create an addon that adds these as bindings to the bindings menu

**Comment by Spanospy** [comment]
Makes sense. I'll be honest, the way I did it was just the quickest and easiest as I based it off of how the disguiser does bindings.

I'll see if I can make sense of your proposed way of doing it when I get home from holiday gatherings!

**Review by EntranceJew — CHANGES_REQUESTED** [review]
I think the concommand implementation works out great, 

https://github.com/TTT-2/TTT2/assets/5711436/08c5e643-b69a-438e-aa8d-7d1971f44523

The only thing I would do is if it is invoked while it's already open on that tab, then it should perhaps instead close the window so when used in this radial, it's easy to close the menu without having to use a separate keypress (pressing the bound buy menu button will close any page)

**Comment by Spanospy** [comment]
> If you want bindings, I'd like to vote against commands as we do not want to make the user use the console.
> 
> I'd appreciate an API that allows you to open tabs (or whatever it is that we will have after the rework)
> 
> That way you can
> 
> * open the menu with function calls in addons
> * create an addon that adds these as bindings to the bindings menu

Do you have anything I can refer to as a "good example" of what you're thinking?

**Comment by Spanospy** [comment]
> First of, yes, a Shop UI and backend overhaul is in the works right now!

Are you referring to https://github.com/TTT-2/TTT2/pull/988 ?

**Comment by Spanospy** [comment]
Also noticed a posted issue that implies it's not desired for the equipment / traitor menu to have equipment-specific tabs: https://github.com/TTT-2/TTT2/issues/1095

With this in mind, I'm not sure how useful it is to have this functionality if only two tabs should live in that menu.

**Comment by TimGoll** [comment]
> Also noticed a posted issue that implies it's not desired for the equipment / traitor menu to have equipment-specific tabs: https://github.com/TTT-2/TTT2/issues/1095
> 
> With this in mind, I'm not sure how useful it is to have this functionality if only two tabs should live in that menu.

Yes, I'm not a big fan of those tabs. But the radio still needs an UI. The new UI can still be opened with your binding. We have to find a good solution for it

**Comment by ZenBre4ker** [comment]
I think we can close this, as we dont want to use the concommands for that and are working on a better solution for the tabs in general.

**Pull request closed without merging**
