### PR TITLE
added preventSprint to doubletap feature

### PR DESCRIPTION
**Pull request by TheNickSkater**
I think preventSprint was forgotten here, added it back

### CODE REVIEW

**Comment by Alf21** [comment]
@menof36go

**Comment by menof36go** [comment]
I totally forgot about the flag. Luckily it seems to be unused as of now, so nobody should have experienced issues regarding the lack of the flag yet. I approve of this change

**Comment by saibotk** [comment]
A general question: 
What does `preventSprint` do other than preventing the Sprint clientside? Or rather, what is the intended use case? @menof36go maybe you can give some insight. Id appreciate that

**Comment by menof36go** [comment]
> 
> 
> A general question:
> What does `preventSprint` do other than preventing the Sprint clientside? Or rather, what is the intended use case? @menof36go maybe you can give some insight. Id appreciate that

Nothing, but it has always been there it seems. I'd just keep it for compatibility

**Pull request merged**
