### PR TITLE
Add locational voice chat range cut-off setting

### PR DESCRIPTION
**Pull request by ruby0b**
#1491

### CODE REVIEW

**Comment by ruby0b** [comment]
Not sure if using 0 as a special value to disable the feature is idiomatic or if I should add a bool that enables/disables the cut-off being active.

**Comment by ruby0b** [comment]
As for the motivation for this feature: by default, you can basically still hear every player from anywhere on the map, they just get *very* quiet at some point which is probably not what most people want.

**Comment by EntranceJew** [comment]
Does this also account for the "local origin" issue where anyone standing near 0,0,0 will be able to hear conversations at a much higher volume due to the speaking player being in the PAS but not the PVS?

**Comment by ruby0b** [comment]
Sorry, I don't know anything about that issue (didn't even know that was a thing). Would that affect distance calculations?
If not then I guess this would fix that since you're guaranteed not to hear anyone outside the given range.

**Comment by EntranceJew** [comment]
It is more like it is a problem that frequently crops up with distance-cutoff because the issue becomes more apparent when the voice range is relatively small but the map is dense, I'm surprised you haven't had it come up.

**Review by saibotk — APPROVED** [review]
Looks very good and i think 0 is fine for disabled 🙌

Thank you so much for improving this.

**Review by Histalek — APPROVED** [review]
Looks good to me :)

using 0 to turn this is off is a good choice

**Pull request merged**
