### PR TITLE
Fetch: Removed fetching avatar icons from Steam

### PR DESCRIPTION
**Pull request by mexikoedi**
Avatar icons are no longer fetched from Steam and are being created via [AvatarImage](https://wiki.facepunch.com/gmod/AvatarImage) instead.
The icon should appear much faster than before and therefore the player will always see an icon. (The fetching from Steam took a while and it was possible to see the default icon instead before the real avatar icon was shown.)
Should also solve the issue which some players from China had because Steam is blocked there.
Tested it on v0.14 and it seemed to work great (saving/loading also works).

### CODE REVIEW

**Comment by saibotk** [comment]
Cant we just switch to the native solution entirely?

**Comment by sbzlzh** [comment]
image
image
It just feels like there's a little extra avatar for this voice

**Comment by TimGoll** [comment]
> Cant we just switch to the native solution entirely?

It was me who suggested doing it that way because the AvatarImage doesn't support all resolutions etc. However I'm open to be convinced to vhange the system completely

**Comment by sbzlzh** [comment]
> > 图像 图像感觉就像这个声音有一个额外的形象
> 
> 我不知道你在说什么。但在我看来，它看起来符合预期

image
That's the box that's out of bounds.

**Comment by TimGoll** [comment]
It's intended that way :D

**Comment by sbzlzh** [comment]
> It's intended that way :D

All right

**Comment by mexikoedi** [comment]
> > Cant we just switch to the native solution entirely?
> 
> It was me who suggested doing it that way because the AvatarImage doesn't support all resolutions etc. However I'm open to be convinced to vhange the system completely

I could look into it if it is possible to remove all the fetching and instead use the solution with `AvatarImage` everywhere if this is wanted?
If it is possible then I think it would be even better (more reliable/faster) than to fetch the images from Steam.

**Comment by TimGoll** [comment]
@mexikoedi if you think it is better that way, then I support that approach

**Comment by sbzlzh** [comment]
What would create downloaded_assets, it doesn't look like it does to me

**Comment by mexikoedi** [comment]
> What would create downloaded_assets, it doesn't look like it does to me

The folder is always created if it doesn't exist under "GarrysMod/garrysmod/data".
I haven't changed that.

**Comment by sbzlzh** [comment]
> The folder is always created if it doesn't exist under "GarrysMod/garrysmod/data".
> I haven't changed that.

I mean, I didn't create the file.

**Comment by sbzlzh** [comment]
I know where it is... : )

**Comment by mexikoedi** [comment]
> > The folder is always created if it doesn't exist under "GarrysMod/garrysmod/data".
> > I haven't changed that.
> 
> I mean, I didn't create the file.

Maybe try it with the newest changes.
I tested it again and it worked. 
For example if I don't have the folder and then join a game it will create the folder with three images (32x32, 64x64 and 184x184) which will be then used. If I already have the folder but without the images it also creates the three images.

**Comment by sbzlzh** [comment]
> > > The folder is always created if it doesn't exist under "GarrysMod/garrysmod/data".
> > > I haven't changed that.
> > 
> > 
> > I mean, I didn't create the file.
> 
> Maybe try it with the newest changes. I tested it again and it worked. For example if I don't have the folder and then join a game it will create the folder with three images (32x32, 64x64 and 184x184) which will be then used. If I already have the folder but without the images it also creates the three images.

Yes, indeed.

**Review by TimGoll — APPROVED** [review]
This looks good to me. I'm just wondering what happens if a player changes their avatar? The same problem probably existed before as well. But this is something we should think about and find a solution for.

**Comment by mexikoedi** [comment]
> This looks good to me. I'm just wondering what happens if a player changes their avatar? The same problem probably existed before as well. But this is something we should think about and find a solution for.

Yes, this is an issue.
Should I try to solve it in this PR?
Maybe get the already existing file and comparing it with the new one. Something in this direction.

**Comment by TimGoll** [comment]
If nobody complains or notifies me that they want to review it, I'll merge this later today, so I can create a prerelease GMA

**Comment by TimGoll** [comment]
> > This looks good to me. I'm just wondering what happens if a player changes their avatar? The same problem probably existed before as well. But this is something we should think about and find a solution for.
> 
> Yes, this is an issue. Should I try to solve it in this PR? Maybe get the already existing file and comparing it with the new one. Something in this direction.

Not in this PR, this issue already existed before. Feel free to do that in another PR. However, if you compare it with the existing file, you downloaded the new one anyway. So there is no real benefit to comparing instead of just replacing it.

**Comment by sbzlzh** [comment]
> This looks good to me. I'm just wondering what happens if a player changes their avatar? The same problem probably existed before as well. But this is something we should think about and find a solution for.

When you change the avatar, it still shows the previous avatar, but you have to delete the stuff in the downloaded_assets to make it up-to-date, but I didn't find any other problems.

**Comment by TimGoll** [comment]
> > This looks good to me. I'm just wondering what happens if a player changes their avatar? The same problem probably existed before as well. But this is something we should think about and find a solution for.
> 
> When you change the avatar, it still shows the previous avatar, but you have to delete the stuff in the downloaded_assets to make it up-to-date, but I didn't find any other problems.

yes, this seems like an issue to me. But that same issue existed before this PR, so it can be fixed at a later point

**Comment by mexikoedi** [comment]
> > > This looks good to me. I'm just wondering what happens if a player changes their avatar? The same problem probably existed before as well. But this is something we should think about and find a solution for.
> > 
> > Yes, this is an issue. Should I try to solve it in this PR? Maybe get the already existing file and comparing it with the new one. Something in this direction.
> 
> Not in this PR, this issue already existed before. Feel free to do that in another PR. However, if you compare it with the existing file, you downloaded the new one anyway. So there is no real benefit to comparing instead of just replacing it.

Ok, then I will fix that in another PR. Then the solution would be calling  `draw.DropCacheAvatar` in the `CreateAvatarMaterial` at the location where it checks if the file exists. Something like that?

**Pull request merged**
