### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by westooooo**

### CODE REVIEW

**Comment by TimGoll** [comment]
uhm?

**Comment by westooooo** [comment]
I want to add a new japanese translation. but I can't do it. what should I do?

**Comment by TimGoll** [comment]
I see you alreaddy forked TTT2. Pull it to your computer ([GitHUb Desktop](https://desktop.github.com/) is really easy for beginners). Add the file. Then commit, push and open a pullrequest.

If you really don't want to get it done by yourself, you can send us the file on discord and we'll incorperate it. However we prefer it over GitHub.

**Comment by Histalek** [comment]
closed in favor of #728

**Pull request closed without merging**
