### PR TITLE
Cleanup: Move round state hooks & remove hook add

### PR DESCRIPTION
**Pull request by saibotk**
This removes the random reseeding every round and also moves the buytable resets to their appropriate functions.

Also this moves the hooks with their documentation to the correct sh_main file, as they are shared.

### CODE REVIEW

**Comment by Alf21** [comment]
@JustHev

**Comment by JustHev** [comment]
In general the PRNG should only be seeded once and it must be seeded before random values are used. It is already seeded server-side in sv_main (which seems okay to me, but I'm not as familiar with the codebase as you guys) and on the client side in cl_scoring, although cl_scoring is only called after the first round.

A followup for clientside randomness is definitely needed, but not as high as a priority as serverside randomness. I'd recommend to not completely remove this call right now but move it to cl_main instead. This ensures that the client is seeded at init time, then once cl_scoring is reworked to not rely on randomseed for correctness (although other addons could rely on all client side PRNG's to have the same state, which would be bad) clientside randomness should be of an acceptable quality.

**Comment by saibotk** [comment]
I explicitly removed it, as it does not make sense to seed it again after it was already seeded when the game mode was initialized.
This might also have caused weird issues with our randomness, as in the original TTT, there is also no reseeding besides the initial seed in the server side init file.

@JustHev About the client side, i think we would not need to move any of that seeding, as for now it really is not important and last but not least with this change it should be similar to the base TTT functionality (randomness-wise).

**Comment by JustHev** [comment]
Fair point. Looking through the GMod lua I see that [they are already seeding the RNG in their lua includes](https://github.com/Facepunch/garrysmod/blob/cf262a1342ccb79831046b98452317ba1a1f9e3b/garrysmod/lua/includes/util.lua#L5) so I wonder if seeding it on the TTT2 side is needed at all.

**Comment by saibotk** [comment]
> The changelos is missing though :P

I don't see a need for a changelog, do you?

**Comment by TimGoll** [comment]
> I don't see a need for a changelog, do you?

Hmm, you're right. I think this fits the already added point in the changelog. However I wanted to be the one remembering you for once. :D

**Comment by saibotk** [comment]
> > I don't see a need for a changelog, do you?
> 
> Hmm, you're right. I think this fits the already added point in the changelog. However I wanted to be the one remembering you for once. :D

Didn't you see i already added the `skip/changelog` label?

**Comment by TimGoll** [comment]
> Didn't you see i already added the `skip/changelog` label?

Nope, I missed this. Thanks!

**Pull request merged**
