### PR TITLE
Localization update

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by Alf21** [comment]
@Satton2 needs to confirm before merging.

**Comment by Satton2** [comment]
I don't like these changes. Around 70% of these changes have translation or grammar mistakes. I'd like to say more, but since I am currently ill, I am not going to do this.

For now, I disapprove these changes.

Also, I have some questions about the English localization file regarding these changes, but I will ask them when I get better.

**Comment by saibotk** [comment]
Take your time, no hurry. Thank you for your effort!

**Comment by Blueberryy** [comment]
@satton2, i could update my pull if you give me fixes for my text.

**Comment by dok441** [comment]
@Blueberryy Если хочешь предложить перевод нет проблем, бери и предлагай сюда же, Саттон скажет тебе, нормальный он или нет. Но как он и сказал выше, он болен и ответит тебе не сразу.

**Pull request closed without merging**
