### PR TITLE
Added British English

### PR DESCRIPTION
**Pull request by NovaDiablox**
The changes are mostly "z" to "s" in some words.

### CODE REVIEW

**Comment by saibotk** [comment]
Hey 👋 

Sorry for the late reply.

I don't feel like there is much benefit in maintaining another region specific language especially since they do not differ that much. 

So i would tend to not include this. But let's hear someone else's opinion on this.

**Comment by NovaDiablox** [comment]
> Hey 👋
> 
> Sorry for the late reply.
> 
> I don't feel like there is much benefit in maintaining another region specific language especially since they do not differ that much.
> 
> So i would tend to not include this. But let's hear someone else's opinion on this.

To be honest I did it for funzies but it still holds value imo. I would like to hear from others as well.

**Comment by Histalek** [comment]
There is some value to this, but i don't think it is worth the effort

Suppose we add a new translation string to the english language, would someone using the british translation realize that string to be missing? Probably not given that there are only some minor or rare differences e.g.:

- `z` -> `s`
- some `o` -> `ou` (as in `colour` or `favourite`)
- some special distinct words like `flashlight` -> `torch`

To be honest i wouldn't even be sure if our base english file is completely american english. It's probably mushed together anyway

**Comment by NovaDiablox** [comment]
> There is some value to this, but i don't think it is worth the effort
> 
> Suppose we add a new translation string to the english language, would someone using the british translation realize that string to be missing? Probably not given that there are only some minor or rare differences e.g.:
> 
> - `z` -> `s`
> - some `o` -> `ou` (as in `colour` or `favourite`)
> - some special distinct words like `flashlight` -> `torch`
> 
> To be honest i wouldn't even be sure if our base english file is completely american english. It's probably mushed together anyway

Yes I agree.

**Pull request closed without merging**
