### PR TITLE
Corpses: Fix multiple corpses

### LINKED ISSUE #611: Calling kill on a dead player causes another corpse to spawn
## Your version of TTT2 (mandatory)

- Workshop version from Steam (v0.7.2b)

## Describe the bug (mandatory)

Calling [kill](https://wiki.facepunch.com/gmod/Player:Kill) on a dead player causes another corpse to spawn.

## To reproduce

Steps to reproduce the behaviour:

1. Kill a player with an explosion for example
2. Right after it, kill the player with the [kill](https://wiki.facepunch.com/gmod/Player:Kill) function

## Expected behaviour

Only one corpse spawns with explosion as the kill reason.

## Additional context

It was working correctly in TTT. It may be caused by a different implementation of [GM:PlayerDeath](https://wiki.facepunch.com/gmod/GM:PlayerDeath).

### PR DESCRIPTION
**Pull request by saibotk**
This removes the timer in sv_player, that would delay handling the death to the next frame, as this leads to multiple corpses etc, when a player dies from damage and a `ply:Kill` command in the same frame.

Don't know why this timer even was introduced, maybe @Alf21 knows something about this?

Fixes #611

### CODE REVIEW

**Comment by Alf21** [comment]
The timer was introduced because `victim:Extinguish()` was called too early, so that a player that burned continued being on fire even if switched into the spec team. Don't know if it's still a thing or got fixed by gmod.

**Comment by saibotk** [comment]
> The timer was introduced because `victim:Extinguish()` was called too early, so that a player that burned continued being on fire even if switched into the spec team. Don't know if it's still a thing or got fixed by gmod.

I checked the TTT source code and they still do it like that, seems to be not that big of a problem and is unavoidable to remove the timer at least for all the other functionality, that is used to handle the death

**Comment by TimGoll** [comment]
@Alf21 why not move `victim:Extinguish()` into the next frame? Wouldn't this solve both problems?

**Comment by saibotk** [comment]
@TimGoll i think we should just keep it as it is done on TTT for now, if the issue comes up again, we can try to fix this with the ugly timer workaround

**Pull request merged**
