### PR TITLE
allow extending item/role menus without detouring as much

### PR DESCRIPTION
**Pull request by EntranceJew**
goes in hand with #1050

### CODE REVIEW

**Review by saibotk — APPROVED** [review]
LGTM

**Review by Histalek — APPROVED** [review]

**Comment by TimGoll** [comment]
Just for my understanding - this is a solution so that you don't have to use the filebased menu creation?

Not that big of a fan of this change. But then again, TTT is already a mess, so who cares I guess :D

**Comment by EntranceJew** [comment]
For stuff that people make, it'll still be significant for them to add their own menus and such, but this was mostly to facilitate putting relevant options next to things that isn't within code an addon developer controls [like I did with SMORE](https://steamcommunity.com/sharedfiles/filedetails/?id=3032725825), which I've also been using to prototype porting some stray ULX-dependent options into the relevant role/item menus to alleviate the number of server addons that don't affect global behavior.

**Comment by TimGoll** [comment]
> For stuff that people make, it'll still be significant for them to add their own menus and such, but this was mostly to facilitate putting relevant options next to things that isn't within code an addon developer controls [like I did with SMORE](https://steamcommunity.com/sharedfiles/filedetails/?id=3032725825), which I've also been using to prototype porting some stray ULX-dependent options into the relevant role/item menus to alleviate the number of server addons that don't affect global behavior.

Thanks. Understandable :)

**Pull request merged**
