### PR TITLE
AFK timer / incomplete player join bookkeeping

### PR DESCRIPTION
**Pull request by EntranceJew**
- add plymeta:IsFullySignedOn
 - overzealous AFK reigned in

now the player will not get booted the very moment they receive a role while joining or between rounds, as long as the idle_limit is greater than 5, the hardcoded check interval

### CODE REVIEW

**Comment by EntranceJew** [comment]
FWIW I think this should immediately be applied pretty much everywhere, but especially to role distribution, so that players do not feel the inclination to beat down players that have not even fully connected but have a role.

**Review by TimGoll — APPROVED** [review]
Huh, that's neat!

I'm wondering I implemented something similar a few years ago, called `plymeta:IsReady`. Should this be replaced by your implementation?

https://github.com/TTT-2/TTT2/blob/4c05a87956b919a159a833b42ac49716a309339f/gamemodes/terrortown/gamemode/client/cl_player_ext.lua#L240-L266

**Review by Histalek — APPROVED** [review]
Definitely a nice addition.

I guess we would need to see if `SIGNONSTATE_FULL` is always the state we need in different cases. (maybe `_PRESPAWN` or `_SPAWN` might be better suited for some things)
For the idle timer i'm fine with either way though.

**Comment by TimGoll** [comment]
From my POV this is ready to merge, but I want @EntranceJew's feedback on my `ply:IsReady` question first so this doesn't get lost. The code in this PR is good imho

**Comment by EntranceJew** [comment]
> Huh, that's neat!
> 
> I'm wondering I implemented something similar a few years ago, called `plymeta:IsReady`. Should this be replaced by your implementation?
> 
> https://github.com/TTT-2/TTT2/blob/4c05a87956b919a159a833b42ac49716a309339f/gamemodes/terrortown/gamemode/client/cl_player_ext.lua#L240-L266

one major benefit of my implementation is that it allows clients and the server to know which players are pending connection as opposed to just the client, so I would say yes for this case, even if the first SetupMove is closer to the first rendered visual frame.

**Comment by TimGoll** [comment]
> > Huh, that's neat!
> > I'm wondering I implemented something similar a few years ago, called `plymeta:IsReady`. Should this be replaced by your implementation?
> > https://github.com/TTT-2/TTT2/blob/4c05a87956b919a159a833b42ac49716a309339f/gamemodes/terrortown/gamemode/client/cl_player_ext.lua#L240-L266
> 
> one major benefit of my implementation is that it allows clients and the server to know which players are pending connection as opposed to just the client, so I would say yes for this case, even if the first SetupMove is closer to the first rendered visual frame.

My implementation is also shared. But I don't care about the fact if the first frame is rendered, I only needed a way to determine if the player is ready to receive net messages. So I guess we should switch over to your system!

**Pull request merged**
