### PR TITLE
ammo capitalization

### PR DESCRIPTION
**Pull request by EntranceJew**
adds greater icon support to community weapons

### CODE REVIEW

**Review by TimGoll — APPROVED** [review]

**Comment by TimGoll** [comment]
will this fix this issue with some third party weapons using the fallback ammo icon?

image

**Comment by EntranceJew** [comment]
yes; some will still be using ammo that doesn't have a type or icon but it should fix those that uses existing ammo types, and for those that it doesn't, the table is public so it can be amended by addons

**Comment by TimGoll** [comment]
Can you make sure to update this in octagonal as well, as soon as this is merged/released?

**Comment by EntranceJew** [comment]
right now AmmoType isn't referenced anywhere in octagonal so it shouldn't be an issue, unless you mean you're working on something to bring them to parity

**Comment by TimGoll** [comment]
> right now AmmoType isn't referenced anywhere in octagonal so it shouldn't be an issue, unless you mean you're working on something to bring them to parity

I'm putting your icon rework from TTT2 base into octagonal right now

**Comment by EntranceJew** [comment]
then yeah, just tag me in the commit message itself and i'll ensure it's there

**Review by Histalek — APPROVED** [review]

**Comment by TimGoll** [comment]
@EntranceJew not that it is merged here, can you update it in octagonal as well? Thanks!

**Pull request merged**
