### PR TITLE
Removed restriction that only team can pickup Radio

### LINKED ISSUE #1125: Equipment/Radio: Traitors cannot pick up innocent radios?
## Your version of TTT2 (mandatory)
- Workshop version from Steam

## Describe the bug (mandatory)

Radio functions as portable tester, because Ts cannot pick up one a detective dropped for others.

## To reproduce

1. drop radio as inno
2. attempt pick up radio as T

## Expected behaviour

T picks up a radio as normal

### PR DESCRIPTION
**Pull request by a7f3**
Possibility of having this as a convar, in the small cases where this is a wanted feature?

Haven't been able to get `-multirun` launch variable working to be able to test this in game, so if someone could test would be great.

Would close #1125

### CODE REVIEW

**Comment by xopez** [comment]
You should also cleanup the language vars since they are don't used anywhere else:
image

**Comment by xopez** [comment]
I can confirm that this fixes it:
https://youtu.be/9DFrVb2G7Nc

**Comment by Histalek** [comment]
i'm somewhat torn on this. while this would solve the issue of #1125 this is also quite a change in behaviour.

With this change Radios can now be 'stolen' from T's as well. Normally a T will already try to hide a radio so it's not that big of a deal, but still worth mentioning.

Personally i would be fine with this change. I would appreciate more opinions on this though.

Maybe we even want to put this under the `Changed` section in the changelog. Thoughts?

**Comment by TimGoll** [comment]
I had the same thoughts as you had. This might be something that is worth a convar actually

**Comment by TimGoll** [comment]
That's a good compromise. The old owner could also be notified if someone from a different Team stellt their Radio.

Or what about only the deployer being able to pick it up again? That way no one can be tested

**Comment by TimGoll** [comment]
> > Or what about only the deployer being able to pick it up again? That way no one can be tested
> 
> That's probably the best way of doing this

C4, Beacon etc also already work that way

**Comment by TimGoll** [comment]
okay @a7f3 here's what you should do:

- make sure only the owner can pick it up
- add a generic string to the language file that says "only the owner is able to pick up this entity" that is displayed as targetID subtitle if the focusing player is not the owner
- replace the key in that case with a radio icon, feel free to hit me up for an icon

**Pull request closed without merging**
