### PR TITLE
Language: Fixed and updated Chinese translation

### PR DESCRIPTION
**Pull request by sbzlzh**

### CODE REVIEW

**Comment by TimGoll** [comment]
Could you elaborate on that part?

> Convert the newly added language into Chinese

Converted? Hasn't it been chinese before?

**Comment by sbzlzh** [comment]
> 



> Could you elaborate on that part?
> 
> > Convert the newly added language into Chinese
> 
> Converted? Hasn't it been chinese before?
That's the part on July 2, 2022

**Comment by sbzlzh** [comment]
> Could you elaborate on that part?
> 
> > Convert the newly added language into Chinese
> 
> Converted? Hasn't it been chinese before?

Sinicize the new ones in this part

**Comment by TimGoll** [comment]
OK so I guess you mean you fixed some translations and added the missing ones?

**Comment by sbzlzh** [comment]
> OK so I guess you mean you fixed some translations and added the missing ones?

That's true

**Review by TimGoll — APPROVED** [review]

**Review by Histalek — APPROVED** [review]

**Pull request merged**
