### PR TITLE
Overhead Icons: Changed detective overhead icon to show to innocents

### PR DESCRIPTION
**Pull request by JustHev**
Innocents are not considered special, so no role icons were shown to
innocents, although Detective Icons should be shown to them.

### CODE REVIEW

**Comment by TimGoll** [comment]
Did you test this if this breaks the overhead icons of other roles?

**Comment by JustHev** [comment]
Yes, the Cupid and Survivalist are not shown to innocents. I tested that by changing the role of some bots mid-round

**Comment by Alf21** [comment]
Additionally to that commit, there should be the fix to display confirmed and revived inno overheads to other innos as well.

**Comment by helaan** [comment]
> Additionally to that commit, there should be the fix to display confirmed and revived inno overheads to other innos as well.
> 
> (e.g. by adding here https://github.com/TTT-2/TTT2/pull/607/files#diff-e75c75314a90594eb6c031ab58bb239eR175 `or ply:RoleKnown()`).

I don't think that is related and should be fixed at this level, special innocents like the survivalists already show revived players role in overhead icons, the only change this PR makes is that normal innocents will also see any overhead icons.

**Comment by JustHev** [comment]
I don't think that is related and should be fixed at this level, special innocents like the survivalists already show revived players role in overhead icons, the only change this PR makes is that normal innocents will also see any overhead icons.

**Comment by TimGoll** [comment]
I was against this PR at first, but @JustHev is right. We should merge this and rework some parts of the role overhead icons in general. But this is out of scope for this community based PR

**Pull request merged**
