### PR TITLE
Added some missing strings

### PR DESCRIPTION
**Pull request by PinoMartirio**
Added some strings that weren't translated

### CODE REVIEW

**Comment by TimGoll** [comment]
could you please resolve the merge conflicts?

**Comment by PinoMartirio** [comment]
Ok, did it

**Comment by TimGoll** [comment]
Okay, so I looked at this. It's nice that you translated some missing strings. However we reworked the language file (see the link I sent you) and therefore the structure is a bit different. So sadly this won't help that much since all further translations should be based on the new file since it is way more easy to manage for you and us

**Comment by PinoMartirio** [comment]
Oh, no worres. I'll look at the link and use that structure. Thank you!

**Comment by TimGoll** [comment]
You can see also this translation to see what I mean: https://github.com/TTT-2/TTT2/pull/502

**Comment by PinoMartirio** [comment]
May I ask you @TimGoll were did you send the link?

**Comment by TimGoll** [comment]
See my edited last comment. And I sent to to you on discord :D

**Comment by PinoMartirio** [comment]
Thank you!

**Comment by TimGoll** [comment]
You're welcome. The missing strings are added as comments. Should be easier this way for you. I'm 99% that I added all missing strings.

**Comment by Histalek** [comment]
#480 needs to be merged before this

**Pull request merged**
