### PR TITLE
Fix: Too narrow line spacings

### PR DESCRIPTION
**Pull request by NickCloudAT**
This fixes to narrow line spacings occuring in eg. the EPOPUP.

Fixes https://github.com/TTT-2/TTT2/issues/1271

### CODE REVIEW

**Review by TimGoll — APPROVED** [review]
As discussed on discord this is a nice fix, thank you. The `lns` variable retuned 2 for a three line text, hence this change is suitable

**Review by saibotk — CHANGES_REQUESTED** [review]
This is only a bandaid fix and we need to dig into why this is happening instead of just adding a +1 without a proper analysis.

There is also no reason for me to believe that this is even correct, since the original code looks correct already.

Also it would be nice to not just throw in a "as discussed on discord" which is not really anything someone else can easily check up on when reviewing.

**Comment by TimGoll** [comment]
> Also it would be nice to not just throw in a "as discussed on discord" which is not really anything someone else can easily check up on when reviewing.

image

**Comment by saibotk** [comment]
This is not a valid argument, just because of an observation of the result and a fix to the result being applied does not mean it is correct.

Why should this start at 0? It counts the table entries in the `lines` variable using `#lines` and should never start to count at 0.

**Comment by TimGoll** [comment]
> This is not a valid argument, just because of an observation of the result and a fix to the result being applied does not mean it is correct.
> 
> Why should this start at 0? It counts the table entries in the `lines` variable using `#lines` and should never start to count at 0.

You're right, this is a valid point. Maybe the table is fucked up in some way because table.Count returns 3, # returns 2. Nick is investigating this right now

**Comment by TimGoll** [comment]
image

for some reason # returns 3 for this table, table.Count returns 4. Weird.

**Comment by saibotk** [comment]
Yes because there is the non-numeric key "TTT2" in there

**Comment by TimGoll** [comment]
> Yes because there is the non-numeric key "TTT2" in there

no, this is not part of the table, the table start at `0`, the line before is a different print

**Comment by saibotk** [comment]
Maybe me or you made the mistake there to start inserting elements at 0 instead of 1.

**Review by ZenBre4ker — APPROVED** [review]
This fix seems okay.
But the actual mistake is, that Lua is 1-indexed. I believe I read that by someone on discord, so if Im just repeating it, Im sorry. So # will ignore 0 entries, which I think are used as strings or maybe they are just ignored by #. -1,-2 also work in lua code.

So the actual mistake with the old code was in line 583 and 597 trying to insert the first string at line 0.

**Review by saibotk — APPROVED** [review]

**Pull request merged**
