### PR TITLE
Added missing translations after Tim's cleanup

### PR DESCRIPTION
**Pull request by Wukerr**
I have manually corrected the Polish translation and it should now have everything that is needed, some of them like TargetID and VSin can't be translated.

### CODE REVIEW

**Comment by TimGoll** [comment]
Nice, please take a look at the CI output

**Comment by TimGoll** [comment]
> some of them like TargetID and VSin can't be translated

Can you explain what you mean with this?

**Comment by Wukerr** [comment]
I mean "TargerID" and "VSkin" themself can not be translated and I don't understand CI output, I edited the file 2 times and I accidentally added space to it and it looks like an error for it. Don't know how to fix.

**Comment by TimGoll** [comment]
Ah, I've kept those words in german as well because these are names. And in line `1208` a `"` is missing

**Comment by Wukerr** [comment]
Everything should be fine right now

**Comment by Histalek** [comment]
#480 needs to be merged before this

**Pull request merged**
