### PR TITLE
Damage Overlay: Fix unscaled damage being shown

### PR DESCRIPTION
**Pull request by ZenBre4ker**
As the amount of damage cant be changed in the hook, we use now the info from dmginfo:GetDamage() instead and therefore take everything that is scaled due to hooks and armor and Karma into account.

Warning: This is untested, but should work in theory!

### CODE REVIEW

**Comment by TimGoll** [comment]
Are you sure that works? Imho we should change the hook to the `GM:PostEntityTakeDamage` hook. See: https://wiki.facepunch.com/gmod/GM:PostEntityTakeDamage

A similar fix was recently done to the hitnumbers addon: https://github.com/ief015/hitnumbers/blob/master/lua/autorun/server/sv_hitdamagenumbers.lua#L374

**Comment by ZenBre4ker** [comment]
Yeah I did that for the addon ^^
It was necessary there because he had no access to the end of the playertakedamage-hook, but we get the same result at the end of gm:playertakedamage as you should get in postentitytakedamage.

But as I said, its just what I think. No tests involved, as I dont want to search for a testpartner 🤷

**Comment by TimGoll** [comment]
> It was necessary there because he had no access to the end of the playertakedamage-hook, but we get the same result at the end of gm:playertakedamage as you should get in postentitytakedamage.

Okay. Is scale player damage included as well? Does this happen before this hook?

**Comment by ZenBre4ker** [comment]
ScalePlayerDamage states, that "use @{GM:EntityTakeDamage} instead if you need to detect ALL damage."
https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/gamemode/server/sv_player.lua#L933

**Review by TimGoll — APPROVED** [review]
I accept this PR because it doesn't break anything. If it is still not fixed after that, we can investigate my comments at a later point.

**Comment by ZenBre4ker** [comment]
Sounds good :)

**Comment by TimGoll** [comment]
Oh, you commented at the same time. Alright then :D

**Pull request merged**
