### PR TITLE
HUD-help Elements: Use global scale factor

### PR DESCRIPTION
**Pull request by TimGoll**
Added scaling to keyhelp and weapon HUD help elements. I also slightly tweaked how shadows are calculated in the draw library to prevent weird glitches at some scale values

### CODE REVIEW

**Comment by TimGoll** [comment]
Can someone on a 1440p or 4k screen verify that this is good? on my FullHD anything bigger than 1.0 causes elements to overlap but this issue shouldn't exist on higher resolutions screens

**Comment by xopez** [comment]
> Can someone on a 1440p or 4k screen verify that this is good? on my FullHD anything bigger than 1.0 causes elements to overlap but this issue shouldn't exist on higher resolutions screens

I can test that tomorrow evening

**Comment by TimGoll** [comment]
> > Can someone on a 1440p or 4k screen verify that this is good? on my FullHD anything bigger than 1.0 causes elements to overlap but this issue shouldn't exist on higher resolutions screens
> 
> I can test that tomorrow evening

if you've got 1440p and the scalefactor is 1.4 then it should look good. At 4k the same holds true for a factor of 2. If you set it to anything besides these values, you probably have the same "issues" I got

**Comment by xopez** [comment]
Seems to work. Tested on 3440x1440px
Scalefactor 3.0
image

Scalefactor 2.0
image

Scalefactor 1.8 (default size)
image

**Comment by TimGoll** [comment]
The default size for your screen should be 1.3 or 1.4. We currently calculate it based on width, but that's a bug. Thanks for the feedback!

**Review by xopez — APPROVED** [review]

**Review by saibotk — APPROVED** [review]

**Review by Histalek — APPROVED** [review]

**Pull request merged**
