### PR TITLE
TargetID-Fix: Initializing convars later

### PR DESCRIPTION
**Pull request by ZenBre4ker**
Now doesnt depend on earlier convar creation.

### CODE REVIEW

**Comment by TimGoll** [comment]
To be honest, I prefer the solution with the convar loader being moved infront of the library loader. This would solve this issue as well. DIdnÄt be discuss this yesterday and decided it was the best solution?

**Comment by ZenBre4ker** [comment]
I actually thought we discussed, that we shouldn't Initialize that at all, because moving libraries shouldn't be a solution. Or in other words, libraries shouldn't depend on each other.
So this is a hotfix until I find more time to properly change the library.

**Comment by TimGoll** [comment]
Yes we discussed to either move the convars to the start or make this library completely independant of thos things.

But I see, this should only be a hotfix and will be later improved?

**Comment by ZenBre4ker** [comment]
Yeah kind of. I didn't really like the option to just move libraries. And so this is still a bad approach. Only problem I see here, is that alf doesn't like TODOs, but this is one.....

**Review by saibotk — APPROVED** [review]

**Review by Histalek — APPROVED** [review]
Please fix the Changelog file, it seems to be

**Review by Alf21 — APPROVED** [review]

**Pull request merged**
