### PR TITLE
Scoreboard: Team indicator

### PR DESCRIPTION
**Pull request by Alf21**
grafik

Added a team indicator in front of every name in the scoreboard. I thought about a role indicator (instead of / as well), but came to this solution (a discussion is always welcome).

### CODE REVIEW

**Review by TimGoll — APPROVED** [review]
Looks good to me! However you might want to add a tooltip with "Team Traitor" etc to make it clear it isn't the role

**Comment by Alf21** [comment]
> 
> 
> Looks good to me! However you might want to add a tooltip with "Team Traitor" etc to make it clear it isn't the role

https://github.com/TTT-2/TTT2/pull/647/files#diff-9da617f14da6d325fe596fb9f097a7beR399 :D

**Comment by TimGoll** [comment]
Oh. I somehow missed this. But it doesn't show that it is a team icon. It just shows "traitor"
Might be confusing if a hitman is confirmed

**Comment by TimGoll** [comment]
closed? o.O

**Comment by Alf21** [comment]
> 
> 
> Oh. I somehow missed this. But it doesn't show that it is a team icon. It just shows "traitor"
> Might be confusing if a hitman is confirmed

Idk what you wanna say ^^. There are no special team icons. And it says for traitors "TEAM Traitors" as defined here: https://github.com/TTT-2/TTT2/blob/37541be47ac40c8828b78be95906f35d140b364a/gamemodes/terrortown/gamemode/shared/lang/english.lua#L16

**Comment by TimGoll** [comment]
Ah, you use the team lang string, of course. Completely forgot this is a thing. Sorry! 
And there are special team icons. Each team has their own icon and you even use it. It is always the main role icon, yes. But it's still a team icon.

But that doesn't matter since I was stupid and you did the right thing

**Comment by Alf21** [comment]
Probably we should add a shadow to match the appearance of the nickname as well as the default icons?

**Comment by TimGoll** [comment]
Btw, a changelog is missing

**Comment by TimGoll** [comment]
> Probably we should add a shadow to match the appearance of the nickname as well as the default icons?

I thought about this as well. Sounds like a good idea. I did not add this as a request since the scoreboard will be reworked at some point anyway.

**Comment by Alf21** [comment]
Added
grafik

**Review by Histalek — APPROVED** [review]
LGTM

**Review by saibotk — APPROVED** [review]

**Pull request merged**
