### PR TITLE
Weapons: Shotgun changes

### PR DESCRIPTION
**Pull request by TW1STaL1CKY**
- Added SWEP.DryFireSound to the weapon base to allow the dryfire sound to be easily changed (now used by the shotgun)
- Applied dryfire sound fix to the shotgun
- Allowed the shotgun to attempt reloading on dryfire
- Interrupting the shotgun's reload looks and feels less jank
- Added a third person reload animation to the shotgun

Side note: while making these changes, I only now realised that the dryfire sound only plays for the player holding the weapon. I think this is fine but I thought I would ask, should we instead let the sound be audible to anyone near the player? I can make another PR if so

### CODE REVIEW

**Comment by Racpy** [comment]
This was a topic I was discussing with others on the TTT2 discord the other day, so I’m glad to see this update!

personally, I think it's weird that the reload sound is only play on client, but I accept it.

**Comment by TimGoll** [comment]
Regarding the dry fire sound: how is it done for other weapons?

**Comment by TW1STaL1CKY** [comment]
> Regarding the dry fire sound: how is it done for other weapons?

A `SWEP.DryFireSound` field was added to weapon_tttbase and is referenced in `SWEP:DryFire`

Since the shotgun doesn't define its own `SWEP:CanPrimaryAttack` anymore, it'll use the default CanPrimaryAttack (which calls `SWEP:DryFire`) defined in the base. All the shotgun does now is set `SWEP.DryFireSound` to the shotgun empty wav path.
Any other weapon wanting to replace just the sound and nothing else can update that field.

**Review by TimGoll — APPROVED** [review]
I took a moment to look through these changes and they look good to me. Especially that it now attempts to reload on dry fire. It always bothered me that shotguns were slightly different. Thanks a lot!

**Pull request merged**
