### PR TITLE
Lang: Add turkish translation

### PR DESCRIPTION
**Pull request by NovaDiablox**
Turkish Language

Warning: The translation is made with the help of a CAT tool which deleted all the '" "' characters. I soon realized it and tried to fix it. Only 900 lines were fixed. I leave rest of it to you guys.

### CODE REVIEW

**Comment by sbzlzh** [comment]
:>

**Comment by sbzlzh** [comment]
Seems like you'll have to do it all by yourself :)

**Comment by TimGoll** [comment]
Thank you. Should be easy enough, I'll do it prior to the next release

**Comment by NovaDiablox** [comment]
> Thank you. Should be easy enough, I'll do it prior to the next release

Thanks a lot, Only if I realized it sooner it wouldn't happen. I still feel ashamed.

**Comment by TimGoll** [comment]
> > Thank you. Should be easy enough, I'll do it prior to the next release
> 
> Thanks a lot, Only if I realized it sooner it wouldn't happen. I still feel ashamed.

No worries. Should be pretty easy with the VS code multi-line cursor

**Comment by TimGoll** [comment]
@NovaDiablox I cleaned up the language file and let our language parser check for errors. There are 7 strings missing in the file. You can find them by searching for `--L.` in the document

**Comment by NovaDiablox** [comment]
> @NovaDiablox I cleaned up the language file and let our language parser check for errors. There are 8 strings missing in the file. You can find them by searching for `--L.` in the document

Alright It is done.

**Review by TimGoll — APPROVED** [review]

**Review by saibotk — APPROVED** [review]
wow, thank you so much for this huge contribution!

Looks fine, but obviously cannot comment on the translations themselves.

**Comment by TimGoll** [comment]
> Thank you too! It was a nice experience for me! I'm always looking for more opportunites :)

There will  be quite a few new oppertunities as soon as the body search rework is merged. :D

**Pull request merged**
