### PR TITLE
docs: Fix partial docstrings

### PR DESCRIPTION
**Pull request by Histalek**
Also 'Doublicated' was bugging me, so i fixed that too.

### CODE REVIEW

**Review by saibotk — APPROVED** [review]
Holy cow finally

**Comment by TimGoll** [comment]
I think it is `@param type name`, you did it the other way around.

And regarding your changed variable name: I think if you change it anyway, you should change it to lowercase as well

**Comment by saibotk** [comment]
Actually that would be somewhat inconsistent with the other vars on an equipment like CanBuy for example

**Comment by Histalek** [comment]
> I think it is `@param type name`, you did it the other way around.

True i mixed it up with how it's done for the lua language server, will fix it.

> And regarding your changed variable name: I think if you change it anyway, you should change it to lowercase as well

AFAIK all SWEP vars are Capitalized and i don't think we should change that

**Review by TimGoll — APPROVED** [review]
I understand your reasoning behind the decision to keep it upper case. I just want to mention that there are already incosistencies. I'm pretty sure there are some variables in the table that are lowercase

**Pull request merged**
