### PR TITLE
Language : Updated Japanese translation

### PR DESCRIPTION
**Pull request by westooooo**
I updated Japanese translation.

### CODE REVIEW

**Comment by saibotk** [comment]
@westooooo thank you for your contribution, could you update your local branch with the latest changes?

(If you dont know how, you can also try to reset the master branch to the latest changes using git and then just delete the content of the existing japanese.lua and paste in your new translation, git will take care about rendering a diff for us)

**Comment by westooooo** [comment]
I updated. If didn't work, please call me.

**Comment by saibotk** [comment]
@westooooo it did not work, you can see below it says "This branch has conflicts that must be resolved". This is an indicator, that you did not update the branch that was used for this PR, you may need to create a new one?

**Comment by TimGoll** [comment]
@westooooo Do you plan of updating this PR? Or should we close it?

**Comment by westooooo** [comment]
oh... I want you to close it. please. sorry...

**Comment by TimGoll** [comment]
Don't feel sorry. We really appreciate your contributions! Maybe you can open a new one at a later point?

**Pull request closed without merging**
