### PR TITLE
MSTACK: Fix missing sound for notification cue

### PR DESCRIPTION
**Pull request by EntranceJew**
[that noise was missing](https://github.com/Facepunch/garrysmod/pull/1983) and i'm tired of seeing developer prints about noises that don't exist

### CODE REVIEW

**Comment by TimGoll** [comment]
huh, interesting. Thanks for bringing this over. I'm wondering if we should also add a convar to disable this, but I guess we probably shouldn't as long as nobody is complaining.

I thought for a moment if we should also rename this sound like they did in TTT, but I don't think that it is likely to clash with anything really

**Review by TimGoll — APPROVED** [review]
but you should probably mention that it is taken from baseTTT, similar to how we did it in the past: https://github.com/TTT-2/TTT2/pull/1156/files

**Comment by EntranceJew** [comment]
it is actually incredibly annoying, but this should motivate people to use less MSTACK prompts, or for us to innovate a recyclable MSTACK id to refresh it like a Toast Notification

**Comment by TimGoll** [comment]
> it is actually incredibly annoying

My fears as well, but this sentence made me chuckle

**Comment by saibotk** [comment]
Actually if it is that annoying, we should really consider either removing this sound cue entirely or we might also add the config convar. Even though i dislike convars, i feel this is nothing many people will enjoy.

**Comment by EntranceJew** [comment]
sounds complicated

**Comment by TimGoll** [comment]
agreed on the sound being annoying. Maybe a different sound would be nice. Maybe the sound used in https://wiki.facepunch.com/gmod/chat.PlaySound

**Comment by EntranceJew** [comment]
> agreed on the sound being annoying. Just tested it. Maybe a different sound would be nice. Maybe the sound used in https://wiki.facepunch.com/gmod/chat.PlaySound

wouldn't it be confusing for the player to potentially hear `HudChat.Message` while both chatting and getting MSTACK popups?

**Comment by TimGoll** [comment]
> > agreed on the sound being annoying. Just tested it. Maybe a different sound would be nice. Maybe the sound used in https://wiki.facepunch.com/gmod/chat.PlaySound
> 
> wouldn't it be confusing for the player to potentially hear `HudChat.Message` while both chatting and getting MSTACK popups?

Probably right, yes. Then let's not do it then.

I've thought about it for a while and do we really want it then? Wouldn't it just be better to not add this annoying feature and remove the bug by removing the sound play that causes an error in the console?

**Comment by EntranceJew** [comment]
if this is blocking something it's gonna need some direction

**Comment by TimGoll** [comment]
nah, it's not blocking. I jsut think we're not sure how to proceed with this. While we all agree it is good to keep feature parity to TTT, it is also kinda annoying

**Comment by EntranceJew** [comment]
attaching here so it doesn't get lost, i did an alternate "heavier" version of the "talk" sfx that is referenced earlier to further distinguish them from each-other
[talk2.zip](https://github.com/TTT-2/TTT2/files/14232219/talk2.zip)

**Comment by saibotk** [comment]
I'd still favor it, if we could just remove this altogether.

**Comment by ZenBre4ker** [comment]
If it's about a vote, I also would vote against the sound and remove the bug.

**Comment by Histalek** [comment]
given that this hasn't existed/worked in the last 12 years or so i would also vote to remove this completely

**Pull request closed without merging**
