### PR TITLE
French translation for TTT2 gamemode

### PR DESCRIPTION
**Pull request by MisterClems**

### CODE REVIEW

**Comment by saibotk** [comment]
Wow thank you very much for a complete translation <3

**Review by TimGoll — CHANGES_REQUESTED** [review]
Please make sure that you have the same lines as the original english translation: https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/gamemode/shared/lang/english.lua

Other that a few missing lines, it looks really good to me. Thank you!

You have a few lines that re still english. Is this intentional?

**Comment by MisterClems** [comment]
problem fixed

**Review by MisterClems — COMMENTED** [review]
problem fixed

**Review by TimGoll — APPROVED** [review]

**Review by saibotk — APPROVED** [review]

**Pull request merged**
