### PR TITLE
use global vectors, especially inside those loops

### PR DESCRIPTION
**Pull request by EntranceJew**

### CODE REVIEW

**Review by Histalek — APPROVED** [review]
Nice

**Comment by TimGoll** [comment]
I think our recent coding style in TTT2 is more like `vectorOrigin`. So frist the type, then what it is. Some parts of the old code still use the old style though. I think this should be changed?

**Comment by Histalek** [comment]
> I think our recent coding style in TTT2 is more like `vectorOrigin`. So frist the type, then what it is. Some parts of the old code still use the old style though. I think this should be changed?

These globals are not controlled by us ;)

**Comment by TimGoll** [comment]
> > I think our recent coding style in TTT2 is more like `vectorOrigin`. So frist the type, then what it is. Some parts of the old code still use the old style though. I think this should be changed?
> 
> These globals are not controlled by us ;)

nevermind then

**Review by TimGoll — APPROVED** [review]

**Pull request merged**
